#!/bin/bash
# Setup script for LiLove iOS App Store automation

echo "🔧 LiLove iOS App Store Automation Setup"
echo "========================================="
echo ""

# Check if running from mobile directory
if [ ! -f "app.json" ]; then
    echo "❌ Error: Please run this script from the mobile directory"
    echo "   cd mobile && ./setup-appstore.sh"
    exit 1
fi

echo "This script will help you configure the iOS App Store automation."
echo ""

# Function to read input with default value
read_with_default() {
    local prompt="$1"
    local default="$2"
    local value
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " value
        echo "${value:-$default}"
    else
        read -p "$prompt: " value
        echo "$value"
    fi
}

# Get App Store Connect API credentials
echo "📋 Step 1: App Store Connect API Credentials"
echo "---------------------------------------------"
echo ""
echo "You need three pieces of information from App Store Connect:"
echo "1. Key ID"
echo "2. Issuer ID"
echo "3. Private Key"
echo ""
echo "Get these from: https://appstoreconnect.apple.com/access/api"
echo ""

ASC_KEY_ID=$(read_with_default "Enter your App Store Connect Key ID" "725AYMVS7J")
ASC_ISSUER_ID=$(read_with_default "Enter your App Store Connect Issuer ID" "")
echo ""
echo "For the Private Key, you have two options:"
echo "1. Paste the key directly (multi-line)"
echo "2. Provide the path to the key file"
echo ""
read -p "Choose option (1 or 2): " key_option
echo ""

if [ "$key_option" = "1" ]; then
    echo "Paste your private key (press Ctrl+D when done):"
    ASC_PRIVATE_KEY=$(cat)
elif [ "$key_option" = "2" ]; then
    read -p "Enter path to private key file: " key_path
    if [ -f "$key_path" ]; then
        ASC_PRIVATE_KEY=$(cat "$key_path")
    else
        echo "❌ File not found: $key_path"
        exit 1
    fi
else
    echo "❌ Invalid option"
    exit 1
fi

# Create .env.local file
echo ""
echo "📝 Step 2: Creating .env.local file"
echo "------------------------------------"
echo ""

cat > .env.local << EOF
# LiLove iOS App Store Connect API Credentials
# Generated by setup-appstore.sh

ASC_KEY_ID=$ASC_KEY_ID
ASC_ISSUER_ID=$ASC_ISSUER_ID
ASC_PRIVATE_KEY="$ASC_PRIVATE_KEY"
EOF

echo "✅ Created .env.local file"
echo ""

# Add to gitignore if not already there
if ! grep -q ".env.local" .gitignore 2>/dev/null; then
    echo ".env.local" >> .gitignore
    echo "✅ Added .env.local to .gitignore"
fi

# Test the credentials
echo ""
echo "🧪 Step 3: Testing credentials"
echo "-------------------------------"
echo ""

# Source the environment file
source .env.local

# Check if fastlane is installed
if ! command -v fastlane &> /dev/null; then
    echo "Installing Fastlane..."
    # Check for Ruby version manager
    if command -v rbenv &> /dev/null; then
        echo "Detected rbenv. Installing fastlane gem in user context..."
        gem install fastlane
    elif command -v rvm &> /dev/null; then
        echo "Detected RVM. Installing fastlane gem in user context..."
        gem install fastlane
    else
        echo "⚠️  Warning: No Ruby version manager (rbenv or RVM) detected."
        echo "   Installing gems globally may fail or modify system Ruby."
        echo "   It is recommended to install a Ruby version manager (rbenv or RVM)."
        echo "   See: https://github.com/rbenv/rbenv or https://rvm.io/"
        echo "   Alternatively, you can install fastlane via Homebrew (macOS):"
        echo "     brew install fastlane"
        echo "   Attempting to install fastlane gem globally..."
        gem install fastlane || {
            echo "❌ Failed to install fastlane gem. Please install a Ruby version manager or use Homebrew."
            exit 1
        }
    fi
fi

echo "Testing App Store Connect API connection..."
if [ ! -d "fastlane" ]; then
    echo "❌ Error: fastlane directory not found"
    exit 1
fi
cd fastlane

# Write the private key to a temporary file with restricted permissions
ASC_PRIVATE_KEY_FILE=$(mktemp -t ASC_PRIVATE_KEY.XXXXXX)
chmod 600 "$ASC_PRIVATE_KEY_FILE"
echo "$ASC_PRIVATE_KEY" > "$ASC_PRIVATE_KEY_FILE"

# Try to validate credentials using the key file
if fastlane run validate_app_store_connect_api_key_json_key \
    key_id:"$ASC_KEY_ID" \
    issuer_id:"$ASC_ISSUER_ID" \
    key_filepath:"$ASC_PRIVATE_KEY_FILE" 2>/dev/null; then
    echo "✅ Credentials are valid!"
else
    echo "⚠️  Could not validate credentials (this might be normal)"
    echo "   You can test by running: ./appstore-submit.sh --metadata-only"
fi

# Remove the temporary key file
rm -f "$ASC_PRIVATE_KEY_FILE"
cd ..

# Summary
echo ""
echo "✅ Setup Complete!"
echo "=================="
echo ""
echo "Next steps:"
echo ""
echo "1. Load the environment variables:"
echo "   source .env.local"
echo ""
echo "2. Add screenshots (required for first submission):"
echo "   See: APP_STORE_AUTOMATION_GUIDE.md"
echo "   Place in: fastlane/metadata/en-US/screenshots/iphone65/"
echo ""
echo "3. Upload metadata to App Store Connect:"
echo "   ./appstore-submit.sh --metadata-only"
echo ""
echo "4. Upload screenshots:"
echo "   ./appstore-submit.sh --screenshots-only"
echo ""
echo "5. Submit your existing build #37 for review:"
echo "   ./appstore-submit.sh --submit-review 37"
echo ""
echo "For complete guide, see: APP_STORE_AUTOMATION_GUIDE.md"
echo ""
