/**
 * OAuth Routes Configuration
 * Auto-generated by setup-oauth.ts
 */

export const OAUTH_ROUTES = {
  google: {
    login: '/api/auth/google',
    callback: '/api/auth/google/callback',
    clientId: process.env.GOOGLE_CLIENT_ID || '',
  },
  apple: {
    login: '/api/auth/apple',
    callback: '/api/auth/apple/callback',
    clientId: process.env.APPLE_CLIENT_ID || 'org.lilove.signin',
  },
  logout: '/api/auth/logout',
  session: '/api/auth/session',
};

export const OAUTH_MOCK_MODE = process.env.OAUTH_MOCK_MODE === 'true';
